version: "3"

services:

  backend:
    build: ./backend
    #volumes:
      #- ./backend:/usr/src/backend
    ports:
      - 4000:4000
    depends_on:
      - database

  database:
    image: mongo:5.0.6
    ports:
      - 27018:27017


  frontend:
    build: ./frontend
    #volumes:
      #- ./frontend:/usr/src/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

networks:
  default:
    ## Use a custom driver
